name: runtime_assert
description: Assert functions.
version: 0.0.1+1
homepage: https://github.com/vivitainc/flutter_runtime_assert

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
